### ISSUE TITLE
Docker image documentation

### ISSUE THREAD

**Issue by jeliasson** [StrangeLoopGames/EcoIssues#18115]
Hi StrangeLoopGames,

After starting a new world with 9.0, using the official docker image `strangeloopgames/eco-game-server`, the `Configs` and `Mods` files are missing on the file system. Furthermore, I can't seem to find any documentation for the image, and the [Dockerfile](https://hub.docker.com/layers/strangeloopgames/eco-game-server/latest/images/sha256-5ade49151cad896a2927c2d428c55c349d275755f11ac09c571ffb5c6207298a?context=explore) gives few clues on what's going on.

```yaml
version: "3.5"
services:
  eco:
    container_name: eco
    hostname: eco
    image: strangeloopgames/eco-game-server
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/eco/server/config:/Configs
    - /home/eco/server/mods:/Mods
    - /home/eco/server/world:/app/Storage
    ports:
    - 3000:3000/udp
    - 3001:3001/tcp
```

I have tried various combinations, including volume mapping `/app` but that just gives me .NET errors during startup.

Anyone have some ideas or can point me to a documentation for the Docker image?
@mirasrael I think you are working with the docker side of things. Maybe you have some tasty internals? 😄

Thanks!
