### ISSUE TITLE
Wiki-Page and Docker-Hub-Request: Docker-Documentation

### ISSUE THREAD

**Issue by jammsen** [StrangeLoopGames/EcoIssues#20214]
Could you please setup a explaination on the docker-hub page which holds to truth on how to use your docker-image for docker-run usage and docker-compose. That way your site with like 100k+ pulls isnt empty and the interwebs holds half truth and we can delivery one full truth about hosting your **AWESOME**game in docker. Maybe we can create a link on your wiki about that Docker-Hub documentation then too.

I've created a template over at: https://raw.githubusercontent.com/jammsen/docker-the-forest-dedicated-server/master/README.md
you can see the output here: https://hub.docker.com/r/jammsen/the-forest-dedicated-server

### Here is a example for Docker-Compose:
```yaml
version: '3.7'

services:
  eco:
    image: strangeloopgames/eco-game-server:latest
    container_name: eco
    ports:
      - 3000:3000/udp
      - 3001:3001/tcp
    volumes:
      - /opt/eco-server/Configs:/app/Configs
      - /opt/eco-server/Storage:/app/Storage
      - /opt/eco-server/Mods:/app/Mods
      - /opt/eco-server/Keys:/root/.aspnet/DataProtection-Keys
    restart: unless-stopped
```
Inspired from this source:  https://gist.github.com/LsHallo/96bf6ef035ef4133fabf065034f76368
