### ISSUE TITLE
Latest server docker image seems to be broken

### ISSUE THREAD

**Issue by lesslwo** [StrangeLoopGames/EcoIssues#23373]
The issue seems to have started at tag [0.9.6.0-beta-staging-2401](https://hub.docker.com/layers/eco-game-server/strangeloopgames/eco-game-server/0.9.6.0-beta-staging-2401/images/sha256-ecdf42c92e2b490a568ac568520455608731dc158e2bf0f15951443e81716626?context=explore)

```bash
username@hostname:~$ docker run strangeloopgames/eco-game-server:latest
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'EcoServer.dll' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet-download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

username@hostname:~$ docker image inspect strangeloopgames/eco-game-server:latest -f "{{.RepoDigests}}"
[strangeloopgames/eco-game-server@sha256:3db30a61e238db33dea08e55ef0031794644ed6068a9eaac8dde601266a84d49]
```

Similar issue reported here https://github.com/StrangeLoopGames/EcoIssues/issues/23360

**Comment by lesslwo** [comment]
It seems like the cause of this is that the file structure of the server is messed up inside the image (the contents of `Config`, `WebClient`, `Mods` folders are instead located in root).

```bash
username@hostname:~$ docker run strangeloopgames/eco-game-server:latest ls /app
Backup.eco.template
Balance.eco.template
Civics.eco.template
DefaultWorld
Difficulty.eco.template
Disasters.eco.template
Eco.Core.pdb
Eco.Gameplay.pdb
Eco.IntegrationTests.dll
Eco.Integrations.Twitch.pdb
Eco.ModKit.pdb
Eco.Networking.ENet.pdb
Eco.Plugins.pdb
Eco.Shared.pdb
Eco.Simulation.pdb
Eco.Stats.pdb
Eco.Twitch.Shared.pdb
Eco.Web.Core.pdb
Eco.WebServer.pdb
Eco.World.pdb
Eco.WorldGenerator.pdb
EcoServer
EcoServer.pdb
EcoSim.eco.template
Features.eco.template
Localization.eco.template
Maintenance.eco.template
ModKit.eco.template
Network.eco.template
NodeGraphControl.pdb
Pause.eco.template
Profanity.eco.template
README.md
Rooms.eco.template
Sleep.eco.template
Stats.eco.template
SteamGameServer.pdb
Storage
Storage.eco.template
UserCode
Users.eco.template
WebBin
World.eco.template
WorldGenerator.eco.template
WorldObjects.eco.template
__core__
install.sh
```

**Comment by lesslwo** [comment]
The only workaround right now I could come up with right now is to copy the `Mods` and `WebClient` folders from the official server download at play.eco and mount them directly into the container (along with `Configs` and `Storage` folders which were already mounted). You also need to override the entrypoint to be `/app/EcoServer`.

```yaml
  eco-server:
    image: docker.io/strangeloopgames/eco-game-server:latest
    command: /app/EcoServer
    volumes:
      - type: bind
        source: /eco-server/Storage
        target: /app/Storage/
      - type: bind
        source: /eco-server/Configs
        target: /app/Configs/
      - type: bind
        source: /eco-server/Mods
        target: /app/Mods/
      - type: bind
        source: /eco-server/Logs
        target: /app/Logs/
      - type: bind
        source: /eco-server/WebClient
        target: /app/WebClient/
```
