### ISSUE TITLE
Eco Docker server not working

### ISSUE THREAD

**Issue by UselessWolfy** [StrangeLoopGames/EcoIssues#25262]
```
services:
  eco:
    image: strangeloopgames/eco-game-server:latest
    container_name: eco
    command:
      - /app/EcoServer
      - -userToken=very long token
    ports:
      - 3000:3000/udp
      - 3001:3001/tcp
    volumes:
      - ./eco-server/Configs:/app/Configs
      - ./eco-server/Storage:/app/Storage
      - ./eco-server/Mods:/app/Mods
    restart: unless-stopped
```
    
```
eco  | [01:13:12] Logged in to Strange Cloud using user token.
eco  | [01:13:12] Eco Server 0.11.1.1 beta release-758, Logged in as UselessWolfy
eco  | [01:13:12] Starting PerformancePlugin                        ...
eco  | [01:13:12] Starting PerformancePlugin                        ... Finished in 0.045 sec
eco  | [01:13:12] Starting ProfilingPlugin                          ...
eco  | [01:13:12] Starting ProfilingPlugin                          ... Finished in 0.000 sec
eco  | [01:13:12] Starting MaintenancePlugin                        ...
eco  | [01:13:12] Starting MaintenancePlugin                        ... Finished in 0.006 sec
eco  | [01:13:12] Server Initialization                             ...
eco  | [01:13:12] Starting FeaturesPlugin                           ...
eco  | [01:13:12] Starting FeaturesPlugin                           ... Finished in 0.005 sec
eco  | [01:13:12] Starting BalancePlugin                            ...
eco  | [01:13:12] Starting BalancePlugin                            ... Finished in 0.003 sec
eco  | [01:13:12] Starting StrangeWorldsPlugin                      ...
eco  | [01:13:12] Starting StrangeWorldsPlugin                      ... Finished in 0.007 sec
eco  | [01:13:12] Starting NetworkManager                           ...
eco  | [01:13:12] Starting NetworkManager                           ... Finished in 0.018 sec
eco  | [01:13:12] Starting DifficultySettings                       ...
eco  | [01:13:12] Starting DifficultySettings                       ... Finished in 0.099 sec
eco  | [01:13:12] Starting ModKitPlugin                             ...
eco  | [01:13:14] Starting ModKitPlugin                             ... Finished in 1.151 sec
eco  | [01:13:14] Server Initialization                             ... Finished in 1.308 sec
eco  | [01:13:14] Failed to start the server. Exception was Exception: WeavingException
eco  | Message:Can't resolve reference to assembly Eco.Core for Eco.Core.PropertyHandling.INotifyPropertyChangedInvoker, Eco.Core
eco  | Source:StrangeLoopGames.PropertyChanged.Fody
eco  |
eco  | Fody.WeavingException: Can't resolve reference to assembly Eco.Core for Eco.Core.PropertyHandling.INotifyPropertyChangedInvoker, Eco.Core
eco  |    at CecilUtils.MakeTypeReference(String assemblyQualifiedName, ModuleDefinition module) in C:\slg\PropertyChanged\PropertyChanged.Fody\CecilUtils.cs:line 26
eco  |    at ModuleWeaver.get_PropertyChangedInvoker() in C:\slg\PropertyChanged\PropertyChanged.Fody\Config\AddPropertyChangedInvokerConfig.cs:line 38
eco  |    at ModuleWeaver.ProcessPropertyChangedInvoker() in C:\slg\PropertyChanged\PropertyChanged.Fody\PropertyChangedInvokerProcessing.cs:line 20
eco  |    at ModuleWeaver.Execute() in C:\slg\PropertyChanged\PropertyChanged.Fody\ModuleWeaver.cs:line 24
eco  |    at Eco.ModKit.Internal.Weaving.RuntimeWeaver.ExecuteWeavers(XElement xWeavers)
eco  |    at Eco.ModKit.Internal.Weaving.RuntimeWeaver.Weave(Stream assemblyStream, Stream symbolsStream, String configPath)
eco  |    at Eco.ModKit.RoslynCompiler.Weave(Stream assemblyStream, Stream symbolsStream)
eco  |    at Eco.ModKit.RoslynCompiler.Compile(AssemblyLoadContext assemblyContext)
eco  |    at Eco.ModKit.RoslynCompiler..ctor(AssemblyLoadContext assemblyContext, String modsDirectory, String modsAssemblyPath)
eco  |    at Eco.ModKit.RoslynCompiler..ctor(String modsDirectory, String modsAssemblyPath)
eco  |    at Eco.ModKit.ModKitPlugin..ctor()
eco  |    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
eco  | Outer Exceptions:
eco  | Exception has been thrown by the target of an invocation.
eco  | [01:13:14] Shutdown finished
eco  | [01:13:14] Errors report:
eco  | Failed to start the server. Exception was Exception: WeavingException
eco  | Message:Can't resolve reference to assembly Eco.Core for Eco.Core.PropertyHandling.INotifyPropertyChangedInvoker, Eco.Core
eco  | Source:StrangeLoopGames.PropertyChanged.Fody
eco  |
eco  | Fody.WeavingException: Can't resolve reference to assembly Eco.Core for Eco.Core.PropertyHandling.INotifyPropertyChangedInvoker, Eco.Core
eco  |    at CecilUtils.MakeTypeReference(String assemblyQualifiedName, ModuleDefinition module) in C:\slg\PropertyChanged\PropertyChanged.Fody\CecilUtils.cs:line 26
eco  |    at ModuleWeaver.get_PropertyChangedInvoker() in C:\slg\PropertyChanged\PropertyChanged.Fody\Config\AddPropertyChangedInvokerConfig.cs:line 38
eco  |    at ModuleWeaver.ProcessPropertyChangedInvoker() in C:\slg\PropertyChanged\PropertyChanged.Fody\PropertyChangedInvokerProcessing.cs:line 20
eco  |    at ModuleWeaver.Execute() in C:\slg\PropertyChanged\PropertyChanged.Fody\ModuleWeaver.cs:line 24
eco  |    at Eco.ModKit.Internal.Weaving.RuntimeWeaver.ExecuteWeavers(XElement xWeavers)
eco  |    at Eco.ModKit.Internal.Weaving.RuntimeWeaver.Weave(Stream assemblyStream, Stream symbolsStream, String configPath)
eco  |    at Eco.ModKit.RoslynCompiler.Weave(Stream assemblyStream, Stream symbolsStream)
eco  |    at Eco.ModKit.RoslynCompiler.Compile(AssemblyLoadContext assemblyContext)
eco  |    at Eco.ModKit.RoslynCompiler..ctor(AssemblyLoadContext assemblyContext, String modsDirectory, String modsAssemblyPath)
eco  |    at Eco.ModKit.RoslynCompiler..ctor(String modsDirectory, String modsAssemblyPath)
eco  |    at Eco.ModKit.ModKitPlugin..ctor()
eco  |    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
eco  | Outer Exceptions:
eco  | Exception has been thrown by the target of an invocation.
eco  | : 1
```

**Comment by D3nnis3n** [comment]
Docker isn't supported by us, unfortunately. This looks like a mod issue, though.

**Comment by UselessWolfy** [comment]
there are no mods. just the official docker compose? but ok

**Comment by D3nnis3n** [comment]
```
services:
  eco-1:
    image: strangeloopgames/eco-game-server:latest
    network_mode: "host"
    command:
      - /app/EcoServer
      - -userToken=
    volumes:
      - /home/servers/games/eco/Configs:/app/Configs
      - /home/servers/games/eco/Storage:/app/Storage
      - /home/servers/games/eco/Mods/UserCode:/app/Mods/UserCode
    restart: unless-stopped
```

Works fine for me on Ubuntu 22.04.1, Docker 27.3.1.
